services:
  - type: web
    name: westley-model
    runtime: python
    rootDir: space
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
